import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import Aboutus from "./components/Aboutus";
import Testimonial from "./components/Testimonial";
import Cards from "./components/Cards";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      {/* hero  */}
      <section className="h-auto md:h-[874px] bg-cover bg-center m-6 mt-0 rounded-xl"
        style={{ backgroundImage: "url('/bg1.png')"}}>
        <div className="w-full max-w-[785px] mx-auto px-4">
          <div className="flex flex-col justify-center items-center h-auto md:h-screen py-8 md:py-0">
            <h1 className="font-poppins text-4xl md:text-64px text-center font-bold leading-[1.2em] md:leading-[76px]">
              Fill Every Seat. Boost Your Business.
            </h1>
            <p className="text-center text-base md:text-2xl pt-6 pb-16 font-Helvetica">
              StubRush helps event venues and theaters sell last-minute tickets
              at discounted prices or for free, maximizing attendance and
              enhancing audience engagement.
            </p>
            <Link   href="/listevent" className="font-inter text-sm md:text-base font-medium bg-blue1 rounded-md p-3 md:p-4">
              List Your Event Now
            </Link>
          </div>
        </div>
      </section>

      {/* Why stubrush  */}
      <Aboutus />
    <Cards />
      

      {/* getting started  */}
      <section className="w-full">
        <div className="w-full max-w-[1344px] px-4 mx-auto">
        <div>
          <h2 className="text-3xl lg:text-4xl font-bold font-poppins text-white text-center">Getting started is simple</h2>
        </div>
        <div className="flex flex-wrap gap-[30px] md:gap-[75px] lg:mt-[75px] lg:mb-[130px] md:py-20 py-16 justify-center">
          <div className="max-w-[380px] bg-gradient-to-b from-yellow1 to-black pt-[60px] px-[25px] pb-[50px] rounded-xl">
            <h4 className="font-poppins font-bold text-2xl text-center">
              1. List Your Event
            </h4>
            <p className="font-Helvetica text-sm text-center pt-3 px-3">
              Submit your event details using our easy online form.
            </p>
          </div>
          <div className="max-w-[380px] bg-gradient-to-b from-yellow1 to-black pt-[60px] px-[25px] pb-[50px] rounded-xl">
            <h4 className="font-poppins font-bold text-2xl text-center">
              2. Promote Your Event
            </h4>
            <p className="font-Helvetica text-sm text-center pt-3 px-3">
              Leverage our platform to reach your audience effectively.
            </p>
          </div>
          <div className="max-w-[380px] bg-gradient-to-b from-yellow1 to-black pt-[60px] px-[25px] pb-[50px] rounded-xl">
            <h4 className="font-poppins font-bold text-2xl text-center">
              3. Sell Tickets
            </h4>
            <p className="font-Helvetica text-sm text-center pt-3 px-3">
              Manage ticket sales and track performance easily.
            </p>
          </div>
        </div>
        <div className="lg:max-w-[1140px] justify-center md:max-w-96 w-full md:mx-auto mt-10 shadow-custom">
          <Link
            href="/listevent"
            className="text-center bg-yellow1 py-2.5 block font-inter text-sm rounded-md font-medium"
          >
            List Your Event Today
          </Link>
        </div>
        </div>
      </section>

      {/* testimonial  */}
      <Testimonial />

      {/* tickets  */}
      <section className="w-full lg:mt-[100px] mb-20">
        <div className="w-full max-w-[1280px] mx-auto px-4">
        <h2 className="text-3xl lg:text-4xl font-bold font-poppins text-white text-center">Find events and tickets</h2>
        <div className="w-full">
        <div className="grid md:grid-cols-3 gap-5 lg:gap-[75px] lg:py-[75px] py-10 justify-center md:justify-start">
          <Image src="/image.png" width={354} height={478} alt="jkfh" />
          <Image src="/image4.png" width={354} height={478} alt="jkfh" />
          <Image src="/image3.png" width={354} height={478} alt="jkfh" />
        </div>
        <div className="flex flex-wrap lg:gap-[75px] gap-5 justify-center">
          <Link href="">
          <Image src="/apple.png" width={200} height={59} alt="jkfh" />
          </Link>
          <Link href="">
          <Image src="/google.png" width={200} height={59} alt="jkfh" />
          </Link>
        </div>
        </div>
        </div>
      </section>
    </>
  );
}

export default page;
